#!/bin/bash

# Define the patch
cat << 'PATCH' > speculative.patch
--- common/speculative.cpp
+++ common/speculative.cpp
@@ -124,8 +124,33 @@
     size_t n_gen_tokens = 0; // number of tokens generated by this implementation.
     size_t n_acc_tokens = 0; // number of tokens accepted by the target model.

-    // TODO: track performance of most recent calls
+    // track performance of most recent calls
+    static const size_t n_recent_max = 16;
+    size_t recent_gen_tokens[n_recent_max] = {0};
+    size_t recent_acc_tokens[n_recent_max] = {0};
+    size_t recent_idx = 0;
+    size_t recent_count = 0;
+
+    double p_accept_recent = 0.0; // recent acceptance rate
+    size_t n_curr_draft_tokens = 0; // number of tokens drafted in the most recent call
+
+    void record_recent_accept(size_t n_accepted) {
+        if (n_curr_draft_tokens == 0) return;
+
+        recent_gen_tokens[recent_idx] = n_curr_draft_tokens;
+        recent_acc_tokens[recent_idx] = n_accepted;
+
+        recent_idx = (recent_idx + 1) % n_recent_max;
+        if (recent_count < n_recent_max) recent_count++;
+
+        size_t total_gen = 0;
+        size_t total_acc = 0;
+        for (size_t i = 0; i < recent_count; ++i) {
+            total_gen += recent_gen_tokens[i];
+            total_acc += recent_acc_tokens[i];
+        }
+
+        if (total_gen > 0) {
+            p_accept_recent = (double)total_acc / total_gen;
+        }
+
+        n_curr_draft_tokens = 0;
+    }
+
     const bool gen_perf = true; // whether to generate performance stats.

     int64_t t_begin_us  = 0; // total time spent in refresh of this implementation in microseconds.
@@ -1271,6 +1296,8 @@
             impl->n_gen_drafts++;
             impl->n_gen_tokens += result.size();

+            impl->n_curr_draft_tokens = result.size();
+
             break; // We have a draft, so break out of the loop and return it.
         }
     }
@@ -1280,14 +1307,13 @@
 }

 void common_speculative_accept(common_speculative * spec, uint16_t n_accepted) {
-    if (n_accepted == 0) {
-        return;
-    }
-
     common_speculative_state * impl = spec->curr_impl;

-    GGML_ASSERT(impl);
+    if (!impl) {
+        return;
+    }

     {
         common_time_meas tm(impl->t_accept_us, !impl->gen_perf);
@@ -1295,6 +1321,8 @@
             impl->n_acc_drafts++;
             impl->n_acc_tokens += n_accepted;
         }
+
+        impl->record_recent_accept(n_accepted);

         impl->accept(n_accepted);
         impl->n_call_accept++;
@@ -1317,14 +1345,15 @@
             str_perf = "";
         }

-        LOG_INF("statistics %s: #calls(b,g,a) = %zu %zu %zu, #gen drafts = %zu, #acc drafts = %zu, #gen tokens = %zu, #acc tokens = %zu%s\n",
+        LOG_INF("statistics %s: #calls(b,g,a) = %zu %zu %zu, #gen drafts = %zu, #acc drafts = %zu, #gen tokens = %zu, #acc tokens = %zu, p_acc_recent = %.3f%s\n",
                 common_speculative_type_to_str(impl->type).c_str(),
                 impl->n_call_begin, impl->n_call_draft, impl->n_call_accept,
                 impl->n_gen_drafts,
                 impl->n_acc_drafts,
                 impl->n_gen_tokens,
                 impl->n_acc_tokens,
+                impl->p_accept_recent,
                 str_perf.c_str());
     }
 }
PATCH

# Apply the patch
patch -p0 < speculative.patch
