import sys

def apply_patch():
    with open('common/speculative.cpp', 'r') as f:
        content = f.read()

    # Part 1: Update common_speculative_state
    search_1 = """    size_t n_gen_tokens = 0; // number of tokens generated by this implementation.
    size_t n_acc_tokens = 0; // number of tokens accepted by the target model.

    // TODO: track performance of most recent calls
    const bool gen_perf = true; // whether to generate performance stats."""

    replace_1 = """    size_t n_gen_tokens = 0; // number of tokens generated by this implementation.
    size_t n_acc_tokens = 0; // number of tokens accepted by the target model.

    // track performance of most recent calls
    static const size_t n_recent_max = 16;
    size_t recent_gen_tokens[n_recent_max] = {0};
    size_t recent_acc_tokens[n_recent_max] = {0};
    size_t recent_idx = 0;
    size_t recent_count = 0;

    double p_accept_recent = 0.0; // recent acceptance rate
    size_t n_curr_draft_tokens = 0; // number of tokens drafted in the most recent call

    void record_recent_accept(size_t n_accepted) {
        if (n_curr_draft_tokens == 0) return;

        recent_gen_tokens[recent_idx] = n_curr_draft_tokens;
        recent_acc_tokens[recent_idx] = n_accepted;

        recent_idx = (recent_idx + 1) % n_recent_max;
        if (recent_count < n_recent_max) recent_count++;

        size_t total_gen = 0;
        size_t total_acc = 0;
        for (size_t i = 0; i < recent_count; ++i) {
            total_gen += recent_gen_tokens[i];
            total_acc += recent_acc_tokens[i];
        }

        if (total_gen > 0) {
            p_accept_recent = (double)total_acc / total_gen;
        }

        n_curr_draft_tokens = 0;
    }

    const bool gen_perf = true; // whether to generate performance stats."""

    content = content.replace(search_1, replace_1)

    # Part 2: Update common_speculative_draft
    search_2 = """            spec->curr_impl = impl.get(); // set current implementation for stats
            impl->n_gen_drafts++;
            impl->n_gen_tokens += result.size();

            break; // We have a draft, so break out of the loop and return it."""

    replace_2 = """            spec->curr_impl = impl.get(); // set current implementation for stats
            impl->n_gen_drafts++;
            impl->n_gen_tokens += result.size();

            impl->n_curr_draft_tokens = result.size();

            break; // We have a draft, so break out of the loop and return it."""

    content = content.replace(search_2, replace_2)

    # Part 3: Update common_speculative_accept
    search_3 = """void common_speculative_accept(common_speculative * spec, uint16_t n_accepted) {
    if (n_accepted == 0) {
        return;
    }

    common_speculative_state * impl = spec->curr_impl;

    GGML_ASSERT(impl);

    {
        common_time_meas tm(impl->t_accept_us, !impl->gen_perf);
        if (n_accepted > 0) {
            impl->n_acc_drafts++;
            impl->n_acc_tokens += n_accepted;
        }

        impl->accept(n_accepted);
        impl->n_call_accept++;
    }
}"""

    replace_3 = """void common_speculative_accept(common_speculative * spec, uint16_t n_accepted) {
    common_speculative_state * impl = spec->curr_impl;

    if (!impl) {
        return;
    }

    {
        common_time_meas tm(impl->t_accept_us, !impl->gen_perf);
        if (n_accepted > 0) {
            impl->n_acc_drafts++;
            impl->n_acc_tokens += n_accepted;
        }

        impl->record_recent_accept(n_accepted);

        impl->accept(n_accepted);
        impl->n_call_accept++;
    }
}"""

    content = content.replace(search_3, replace_3)

    # Part 4: Update common_speculative_print_stats
    search_4 = """        LOG_INF("statistics %s: #calls(b,g,a) = %zu %zu %zu, #gen drafts = %zu, #acc drafts = %zu, #gen tokens = %zu, #acc tokens = %zu%s\\n",
                common_speculative_type_to_str(impl->type).c_str(),
                impl->n_call_begin, impl->n_call_draft, impl->n_call_accept,
                impl->n_gen_drafts,
                impl->n_acc_drafts,
                impl->n_gen_tokens,
                impl->n_acc_tokens,
                str_perf.c_str());"""

    replace_4 = """        LOG_INF("statistics %s: #calls(b,g,a) = %zu %zu %zu, #gen drafts = %zu, #acc drafts = %zu, #gen tokens = %zu, #acc tokens = %zu, p_acc_recent = %.3f%s\\n",
                common_speculative_type_to_str(impl->type).c_str(),
                impl->n_call_begin, impl->n_call_draft, impl->n_call_accept,
                impl->n_gen_drafts,
                impl->n_acc_drafts,
                impl->n_gen_tokens,
                impl->n_acc_tokens,
                impl->p_accept_recent,
                str_perf.c_str());"""

    content = content.replace(search_4, replace_4)

    with open('common/speculative.cpp', 'w') as f:
        f.write(content)

if __name__ == "__main__":
    apply_patch()
