//! Raw FFI bindings to the in-tree llama.cpp (1-bit-turbo HIP fork).
//!
//! Generated by `bindgen` in `build.rs` from the in-tree `include/llama.h` + `ggml/include/*.h`,
//! linked against the prebuilt `build-hip/bin/*.so` HIP artifacts. This crate is raw bindings only;
//! the safe RAII wrappers (`LlamaModel`/`LlamaContext`/`LlamaBatch`) live in `rs_llama_cpp_core`.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    rustdoc::all,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod smoke {
    use super::*;
    use std::ffi::CStr;

    /// Proves the FFI actually LINKS against the prebuilt `build-hip/bin/libllama.so` and that
    /// the `.so` resolves at runtime (via the rpath emitted by `build.rs`). `llama_print_system_info`
    /// needs no model and no GPU init, so it is the minimal end-to-end linkage proof.
    #[test]
    fn links_and_reports_system_info() {
        let info = unsafe { llama_print_system_info() };
        assert!(!info.is_null(), "llama_print_system_info returned null");
        let s = unsafe { CStr::from_ptr(info) }.to_string_lossy();
        assert!(!s.is_empty(), "empty system info");
        eprintln!("llama.cpp system info: {s}");
    }
}
